export const localProducts = [
  {
    id: 1,
    title: "Laptop",
    price: 1200,
    rating: 4.5,
    stock: 5,
    category: "laptops",
    tags: ["computer", "electronics", "office"],
    thumbnail: "https://dummyjson.com/icon/1/150",
  },
  {
    id: 2,
    title: "Smartphone",
    price: 800,
    rating: 4.2,
    stock: 15,
    category: "phones",
    tags: ["mobile", "electronics"],
    thumbnail: "https://dummyjson.com/icon/2/150",
  },
  {
    id: 3,
    title: "Headphones",
    price: 100,
    rating: 4.0,
    stock: 3,
    category: "audio",
    tags: ["audio", "electronics"],
    thumbnail: "https://dummyjson.com/icon/3/150",
  },
  {
    id: 4,
    title: "Mechanical Keyboard",
    price: 50,
    rating: 3.8,
    stock: 20,
    category: "accessories",
    tags: ["computer", "accessories"],
    thumbnail: "https://dummyjson.com/icon/4/150",
  },
  {
    id: 5,
    title: "Monitor 24 inch",
    price: 300,
    rating: 4.3,
    stock: 8,
    category: "laptops",
    tags: ["computer", "electronics"],
    thumbnail: "https://dummyjson.com/icon/5/150",
  },
];